---
- name: install httpd
  hosts: all
  become: true
  tasks:
  - name: install the package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "Amazon"

  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "Amazon"

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Ubuntu"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Ubuntu"
  
  - name: copy.index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
