---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
      dest: /opt

  - name: untar packages
    ansible.builtin.unarchive: 
      src: /opt/apache-tomcat-9.0.76.tar.gz
      dest: /opt
      remote_src: yes

  - name: add the execution permissions
    file:
      path: /opt/apache-tomcat-9.0.76/bin/startup.sh
      mode: 0777

  - name: start the services
    shell: nohup ./startup.sh       
    args:
      chdir: /opt/apache-tomcat-9.0.76/bin
