---
- name: uninstall httpd
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat" 

  - name: uninstall httpd
    yum:
      name: httpd
      service: removed
    when: ansible_os_family == "RedHat" 

  - name: uninstall apache2
    service:
      name: httpd
      state: removed
    when: ansible_os_family == "Debian"

  - name: uninstall apache2
    apt:
      name: httpd
      state: removed
    when: ansible_os_family == "Debian"



